version: '3'
services:
  apigateway:
    image: myapp-api  # Use the image name you tagged when building
    ports:
      - "8001:8001"
    depends_on:
      - usersms
      - bookms
      - loansms

  usersms:
    image: myapp-usersms  # Use the image name you tagged when building
    ports:
      - "8002:8002"

  bookms:
    image: myapp-bookms  # Use the image name you tagged when building
    ports:
      - "8000:8000"

  loansms:
    image: myapp-loansms  # Use the image name you tagged when building
    ports:
      - "8003:8003"

