version: '3'
services:
  apigateway:
    build:
      context: ./ApiGate
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - usersms
      - bookms
      - loansms

  usersms:
    build:
      context: ./UsersMS
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  bookms:
    build:
      context: ./BooksMS
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  loansms:
    build:
      context: ./loansMS
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
