# Generated by Django 5.0.2 on 2024-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField()),
                ('summary', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('pub_year', models.DateField(verbose_name='date published')),
                ('coverimg', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
