# Generated by Django 5.0.2 on 2024-02-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
