# Generated by Django 5.0.2 on 2024-02-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksMS', '0002_alter_books_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Title',
            new_name='title',
        ),
    ]
