# Generated by Django 5.0.2 on 2024-04-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksMS', '0003_rename_title_books_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksMS.authors'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
